### ISSUE TITLE
use other dataset

### ISSUE THREAD

**Issue by bookkkker** [GrandpaXun242/AdaBLDM#15]
dear authors, now I need to generate defects on my pcb(print circuit board) dataset, it's a dataset including 5 kinds of defects. can you please tell me how should I correct your code to generate my photos. Thank you!!

**Comment by GrandpaXun242** [comment]
1. Fine-tune the stable diffusion on your pcb dataset.
2. Ensure your image size in 256x256.
3. Making Trimap  and Text Prompt for training time.
4. Testing.
