### ISSUE TITLE
The output dataset

### ISSUE THREAD

**Issue by 20220201yyds** [GrandpaXun242/AdaBLDM#2]
Hello，what you have done is impressive！Well，I am currently busy completing my undergraduate project and need some defect images to train my pixel refinement model. Is it possible to get your after trained MVTecAD dataset? I can receive the dataset personally or through the cloud drive if necessary. This will be a great help to me. Looking forward to your reply.

**Comment by GrandpaXun242** [comment]
Hi , I will release the train and test code in recent day ( 3-4 days). You can generate  MVTecAD dataset by yourself.
