### ISSUE TITLE
A error when run the code

### ISSUE THREAD

**Issue by szgy66** [GrandpaXun242/AdaBLDM#4]
Dear author, when I run the code with command,`python ./foreground_predictor/foreground_predictor.py`,there is a mistake
`Traceback (most recent call last):
  File "./foreground_predictor/foreground_predictor.py", line 10, in <module>
    from models import  EfficientnetPM
  File "/home/401229/AdaBLDM-main/foreground_predictor/models.py", line 1, in <module>
    from futils import FeaturesCollector, load_ckpt
ImportError: cannot import name 'FeaturesCollector' from 'futils' (/home/401229/AdaBLDM-main/foreground_predictor/futils.py)`

I checked the futils.py file, there is no FeaturesCollector function, what should I do with it?

**Comment by GrandpaXun242** [comment]
let me see see.

**Comment by GrandpaXun242** [comment]
I update the class named " FeatureCollector" . And you can see the detail from **https://github.com/flyinghu123/CPR/blob/master/tools/generate_foreground.py**.
