### ISSUE TITLE
Training epochs

### ISSUE THREAD

**Issue by TerryMelody** [GrandpaXun242/AdaBLDM#7]
https://g/GrandpaXun242/AdaBLDM/blob/44a71f07dc62d4477cc6255a96e5defe2c430b3c/train.py#L34
Hello dear authors! I wonder how many epochs I should set in training.

**Comment by GrandpaXun242** [comment]
About 20k iteration and batch_size = 32.

**Comment by TerryMelody** [comment]
> About 20k iteration and batch_size = 32.

Thanks for your reply!

**Comment by jmlee99o** [comment]
You mean , setting as 2700 epochs / 32 batchs when the training datasets are 170?
