### ISSUE TITLE
Generation of data sets with spatial structure

### ISSUE THREAD

**Issue by szgy66** [GrandpaXun242/AdaBLDM#8]
Dear author, I have trained and tested the code in the bottle/broken_large category in the mvtec_ad dataset, and I have only used a small class (broken_large), which works well. However, there is a small problem, because the location of the generated mask is random, but for the category of bottle, its borken only occurs on the ring, which means that this kind of data has a relative spatial structure. I have found that this method has poor effect on this situation, may I ask how to improve it

**Comment by GrandpaXun242** [comment]
I think that making a realistic defect in bottle should be design a special mask which arounds the bottle ring.

**Comment by szgy66** [comment]
> I think that making a realistic defect in bottle should be design a special mask which arounds the bottle ring.

Thanks for your reply. For the last question, I only use broken_large in bottle to train the network and test it again, which can also generate a good defect sample, but all mvtec data sets are used for training in this project. May I ask what is the advantage of this

**Comment by GrandpaXun242** [comment]
> > I think that making a realistic defect in bottle should be design a special mask which arounds the bottle ring.
> 
> Thanks for your reply. For the last question, I only use broken_large in bottle to train the network and test it again, which can also generate a good defect sample, but all mvtec data sets are used for training in this project. May I ask what is the advantage of this

My machine is too poor, only setting a pipeline trains a small defect class.
